spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@kosa402.iptime.org:1521:ORCL
    username: user_gasan_team1
    password: oracle
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

mybatis:
  config-location: classpath:mybatis/mapper-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
